import os
import shutil
import sys
from pathlib import Path

import duckdb
import networkx as nx
from rich.console import Console
from rich.panel import Panel

from mallard.transpiler import transpile_to_duckdb

console = Console()
import mallard.transpiler
print("Using transpiler from:", mallard.transpiler.__file__)

def clean_cache():
    """
    Purge .mallard/ database cache and temporary artifacts.
    """
    cache_dir = Path(".mallard")
    if cache_dir.exists() and cache_dir.is_dir():
        shutil.rmtree(cache_dir)

def table_exists(con, table_name: str) -> bool:
    """Check if a table already exists in the DuckDB database."""
    result = con.execute(
        f"SELECT count(*) FROM information_schema.tables WHERE table_name = '{table_name}'"
    ).fetchone()
    return result[0] > 0

def execute_dag(dag: nx.DiGraph, selected_nodes: list[str], full_refresh: bool = False):
    """
    Executes transformed models on DuckDB.
    Runs compiled Dataform assertions against local outputs; if assertions fail, 
    Mallard outputs a styled [WARNING] box in the terminal without interrupting execution.
    """
    import re
    
    def clean_dataform_scripts(sql: str) -> str:
        """Strip BigQuery procedural syntax (DECLARE, SET, IF) generated by Dataform."""
        # Remove DECLARE blocks
        sql = re.sub(r"(?i)DECLARE\s+[^;]+;", "", sql)
        # Remove SET blocks
        sql = re.sub(r"(?i)SET\s+[^;]+;", "", sql)
        # Unwrap IF table_exists THEN ... END IF;
        sql = re.sub(r"(?i)IF\s+table_exists\s+THEN\s+(.*?)\s+END\s+IF\s*;", r"\1", sql, flags=re.DOTALL)
        return sql.strip()

    os.makedirs(".mallard", exist_ok=True)
    db_path = ".mallard/cache.duckdb"
    
    # We must topological sort the selected nodes to run them in dependency order
    subgraph = dag.subgraph(selected_nodes)
    try:
        ordered_nodes = list(nx.topological_sort(subgraph))
    except nx.NetworkXUnfeasible:
        console.print("[bold red]Cycle detected in dependencies. Cannot execute.[/bold red]")
        return

    con = duckdb.connect(db_path)

    for node_id in ordered_nodes:
        node_data = dag.nodes[node_id]
        action_type = node_data.get("type")
        query = node_data.get("query")
        
        target = node_data.get("target", {})
        schema = target.get("schema")
        name = target.get("name")
        table_name = f"{schema}_{name}"

        if action_type == "table" or action_type == "view":
            pass
            
            # Need to transform BigQuery ref syntax like `database.schema.table` to `schema_table`
            # For simplicity in this demo we rely on transpiler or user to use plain SQL 
            # In a full Dataform compiler the ${ref()} is already expanded to database.schema.table
            # We'll do a naive replacement of the project ID to the local schema for known sources.
            
            # Use transpiler
            duckdb_sql = transpile_to_duckdb(query)
            
            try:
                try:
                    con.execute(f"DROP VIEW IF EXISTS {table_name}")
                except duckdb.CatalogException:
                    pass
                try:
                    con.execute(f"DROP TABLE IF EXISTS {table_name}")
                except duckdb.CatalogException:
                    pass
                
                if action_type == "view":
                    con.execute(f"CREATE VIEW {table_name} AS {duckdb_sql}")
                else:
                    con.execute(f"CREATE TABLE {table_name} AS {duckdb_sql}")
                    
                # Fetch row count
                row_count = con.execute(f"SELECT count(*) FROM {table_name}").fetchone()[0]
                console.print(f"✅ [green]{node_id}[/green] [dim]({row_count} rows)[/dim]")
            except Exception as e:
                console.print(f"[bold red]Error executing {node_id}: {e!s}[/bold red]")
                print("==================== FAILED SQL ====================")
                try:
                    print(duckdb_sql)
                except:
                    pass
                print("====================================================")

        elif action_type == "incremental":
            pass
            
            try:
                is_full_refresh = full_refresh or not table_exists(con, table_name)

                if is_full_refresh:
                    # BEHAVIOR 1: Full rebuild
                    pass
                    duckdb_sql = transpile_to_duckdb(query)
                    try:
                        con.execute(f"DROP VIEW IF EXISTS {table_name}")
                    except duckdb.CatalogException:
                        pass
                    try:
                        con.execute(f"DROP TABLE IF EXISTS {table_name}")
                    except duckdb.CatalogException:
                        pass
                    con.execute(f"CREATE TABLE {table_name} AS {duckdb_sql}")
                else:
                    # BEHAVIOR 2: Incremental Run
                    
                    # 1. Run Pre-Operations
                    for pre_op in node_data.get("incrementalPreOps", []):
                        cleaned_op = clean_dataform_scripts(pre_op)
                        if cleaned_op:
                            con.execute(transpile_to_duckdb(cleaned_op))

                    # 2. Extract the incremental query (fallback to base query if none exists)
                    inc_query = node_data.get("incrementalQuery") or query
                    duckdb_inc_sql = transpile_to_duckdb(inc_query)

                    # 3. Apply unique key logic (Merge/Upsert vs standard Append)
                    unique_key = node_data.get("uniqueKey")
                    if unique_key:
                        # DuckDB doesn't have primary keys defined on CTAS tables,
                        # so we use a standard Delete-then-Insert transaction.
                        keys_str = ", ".join(unique_key)
                        delete_sql = f"""
                            DELETE FROM {table_name}
                            WHERE ({keys_str}) IN (
                                SELECT {keys_str} FROM ({duckdb_inc_sql})
                            )
                        """
                        con.execute(delete_sql)

                    # 4. Insert new records
                    con.execute(f"INSERT INTO {table_name} {duckdb_inc_sql}")

                    # 5. Run Post-Operations
                    for post_op in node_data.get("incrementalPostOps", []):
                        cleaned_op = clean_dataform_scripts(post_op)
                        if cleaned_op:
                            con.execute(transpile_to_duckdb(cleaned_op))

                # Fetch row count
                row_count = con.execute(f"SELECT count(*) FROM {table_name}").fetchone()[0]
                console.print(f"✅ [green]{node_id}[/green] [dim]({row_count} rows)[/dim]")
            except Exception as e:
                console.print(f"[bold red]Error executing {node_id}: {e!s}[/bold red]")
                print("==================== FAILED SQL ====================")
                try:
                    print(duckdb_sql)
                except:
                    pass
                print("====================================================")
                
        elif action_type == "assertion":
            pass
            duckdb_sql = transpile_to_duckdb(query)
            try:
                result = con.execute(duckdb_sql).fetchall()
                if result and len(result) > 0:
                    # Assertion failed (returns rows)
                    error_msg = f"[bold red]Assertion {node_id} failed![/bold red]\n"
                    error_msg += f"Returned {len(result)} failing rows.\n"
                    error_msg += f"Query:\n{duckdb_sql}"
                    
                    console.print(Panel(error_msg, title="[bold red]ERROR[/bold red]", border_style="red"))
                    con.close()
                    sys.exit(1)
                else:
                    console.print(f"✅ [green]{node_id}[/green]")
            except SystemExit:
                raise
            except Exception as e:
                console.print(f"[bold red]Error executing assertion {node_id}: {e!s}[/bold red]")
                con.close()
                sys.exit(1)
                
        elif action_type == "operation":
            pass
            queries = node_data.get("queries", [])
            for q in queries:
                duckdb_sql = transpile_to_duckdb(q)
                try:
                    con.execute(duckdb_sql)
                except Exception as e:
                    console.print(f"[bold red]Error executing operation {node_id}: {e!s}[/bold red]")
            console.print(f"✅ [green]{node_id}[/green]")
            
    con.close()
